version: '2'
services:
  web:
    build:
      context: ./
      dockerfile: ./env/web/Dockerfile
    environment:
      VIRTUAL_HOST: bingosync.mdel.io
    ports:
     - "5000:5000"
    command: npm start
    links:
     - redis
  redis:
    image: redis
