default:
  types:
    - { code: 'oot-normal',      url: "http://speedrunslive.com/tools/oot-bingo",  label: "OoT Bingo" }
    - { code: 'oot-short',       url: "http://speedrunslive.com/tools/oot-bingo",  label: "OoT Short Bingo",                 params: { mode: "short" } }
    - { code: 'oot-short-xlptv', url: "http://bingo.xlptv.com",                    label: "OoT Short Bingo (xlptv edition)", params: { mode: "short" } }
    - { code: 'mm-normal',       url: "http://speedrunslive.com/tools/mm-bingo",   label: "MM Bingo" }
    - { code: 'mm-short',        url: "http://speedrunslive.com/tools/mm-bingo",   label: "MM Short Bingo",                  params: { mode: "short" } }
    - { code: 'sm64',            url: "http://speedrunslive.com/tools/sm64-bingo", label: "SM64 Bingo" }
    - { code: 'sms-nkiller',     url: "http://nkiller.webs.com/bingo/sms/newest/", label: "SMS (nkiller)" }
