default:
  types:
    - { code: 'oot-normal', url: "http://speedrunslive.com/tools/oot-bingo", label: "OoT Normal" }
    - { code: 'oot-short',  url: "http://speedrunslive.com/tools/oot-bingo", label: "OoT Short", params: { mode: "short" } }

